# Generated by Django 3.2 on 2023-05-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'пользователь'), ('admin', 'администратор'), ('moderator', 'модератор')], default='user', max_length=10, verbose_name='Тип пользователя'),
        ),
    ]
