# Generated by Django 3.2 on 2023-05-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230525_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='secret_key',
            new_name='confirmation_code',
        ),
    ]
