# Generated by Django 3.2 on 2023-06-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'пользователь'), ('admin', 'администратор'), ('moderator', 'модератор')], default='user', max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
